[package]
name = "hab"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
build = "../build-habitat.rs"
workspace = "../../"

[[bin]]
name = "hab"
doc = false

[dependencies]
clippy = {version = "*", optional = true}
base64 = "*"
ansi_term = "*"
env_logger = "*"
hyper = "0.10"
handlebars = { version = "*", default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
pbr = "*"
regex = "*"
retry = "*"
serde = "*"
serde_derive = "*"
toml = { version = "*", default-features = false }
url = "*"
walkdir = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_common]
path = "../common"

[dependencies.habitat_depot_client]
git = "https://github.com/habitat-sh/builder.git"

[dependencies.habitat_api_client]
git = "https://github.com/habitat-sh/builder.git"

[dependencies.habitat_http_client]
git = "https://github.com/habitat-sh/builder.git"

[dependencies.uuid]
version = "*"
features = ["v4"]

[dev-dependencies]
tempdir = "*"

[features]
default = []
functional = []
